{"name": "test_register[Create user - username Is Above Max Value]", "status": "failed", "statusDetails": {"message": "AssertionError: FAILURE: \u001b[31massert 200 == 400\ntests\\test_api.py:41 in test_register() -> check.equal(response.status_code,\n\u001b[39m\n------------------------------------------------------------\nFailed Checks: 1", "trace": "FAILURE: \u001b[31massert 200 == 400\ntests\\test_api.py:41 in test_register() -> check.equal(response.status_code,\n\u001b[39m\n------------------------------------------------------------\nFailed Checks: 1"}, "attachments": [{"name": "log", "source": "99556219-b689-4231-85c8-e3c63d10fcb8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'Case': 'Create user - username Is Above Max Value', 'Test Type': 'Negative', 'Request_Body': {'firstName': 'RzNaJgmdcFZtSFbgJodbFyNnTF', 'lastName': 'oXYrxwiNHAdZFjgpQamBTCjYLk', 'username': 'jYtpIC3615945', 'password': '\"\\\\#!(-*'}}"}], "start": 1670168742140, "stop": 1670168742862, "uuid": "afbbe02b-6117-4d5a-b4b7-6c17dee444f2", "historyId": "dcbd3e1304931c4205a7e9938d6efaff", "testCaseId": "bd51a8de3249e024de618e4e17a0a343", "fullName": "tests.test_api.TestApi#test_register", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "DESKTOP-EGG762M"}, {"name": "thread", "value": "11972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}