{"name": "test_register[Create user - Firstname Is Above Max Value]", "status": "failed", "statusDetails": {"message": "AssertionError: FAILURE: \u001b[31massert 200 == 400\ntests\\test_api.py:41 in test_register() -> check.equal(response.status_code,\n\u001b[39m\n------------------------------------------------------------\nFailed Checks: 1", "trace": "FAILURE: \u001b[31massert 200 == 400\ntests\\test_api.py:41 in test_register() -> check.equal(response.status_code,\n\u001b[39m\n------------------------------------------------------------\nFailed Checks: 1"}, "attachments": [{"name": "log", "source": "a36479c4-d364-4c0a-aedf-82e7eb40d240-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'Case': 'Create user - Firstname Is Above Max Value', 'Test Type': 'Negative', 'Request_Body': {'firstName': 'UpIwAeeJoDlLkmCJXzcaLhDzoVXjmLqQKasLKZUxJLnSXvbeFNx', 'lastName': 'hSclfOEAxltfxUzBoivSKueTJa', 'username': 'Ivke1715', 'password': 'aw4|,^'}}"}], "start": 1670168737460, "stop": 1670168738267, "uuid": "4bfcbe61-f155-4e11-851c-5883c989132f", "historyId": "bbeaf2b28162a6cde479d2a50b55f628", "testCaseId": "bd51a8de3249e024de618e4e17a0a343", "fullName": "tests.test_api.TestApi#test_register", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "DESKTOP-EGG762M"}, {"name": "thread", "value": "11972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}