{"name": "test_register[Create user - Firstname & Lastname & username Are Above Max Value]", "status": "failed", "statusDetails": {"message": "AssertionError: FAILURE: \u001b[31massert 200 == 400\ntests\\test_api.py:41 in test_register() -> check.equal(response.status_code,\n\u001b[39m\n------------------------------------------------------------\nFailed Checks: 1", "trace": "FAILURE: \u001b[31massert 200 == 400\ntests\\test_api.py:41 in test_register() -> check.equal(response.status_code,\n\u001b[39m\n------------------------------------------------------------\nFailed Checks: 1"}, "attachments": [{"name": "log", "source": "a1db84a5-b830-4e5a-8617-fad5ab3b13f9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'Case': 'Create user - Firstname & Lastname & username Are Above Max Value', 'Test Type': 'Negative', 'Request_Body': {'firstName': 'ZtVpIImmBvKbYkFzboYGLIgTSmYcrurqnMkUnLEoqAwcLyouvkI', 'lastName': 'mjBRwSOdAstuQziTojyKqBFQmvuYgaPRRYhjjoeQUMBGfcdGYwq', 'username': 'ceFHMN1604973', 'password': 'F0)|'}}"}], "start": 1670168739914, "stop": 1670168740678, "uuid": "b1d88707-1962-4439-afe1-b4a89f680f9d", "historyId": "fca2606dd4821deb4163330ed3881bfe", "testCaseId": "bd51a8de3249e024de618e4e17a0a343", "fullName": "tests.test_api.TestApi#test_register", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "DESKTOP-EGG762M"}, {"name": "thread", "value": "11972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}