{"name": "test_register[Create user - Firstname & username Are Above Max Value]", "status": "failed", "statusDetails": {"message": "AssertionError: FAILURE: \u001b[31massert 200 == 400\ntests\\test_api.py:41 in test_register() -> check.equal(response.status_code,\n\u001b[39m\n------------------------------------------------------------\nFailed Checks: 1", "trace": "FAILURE: \u001b[31massert 200 == 400\ntests\\test_api.py:41 in test_register() -> check.equal(response.status_code,\n\u001b[39m\n------------------------------------------------------------\nFailed Checks: 1"}, "attachments": [{"name": "log", "source": "4a3352e6-927e-4e1f-86bd-ca961c733396-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'Case': 'Create user - Firstname & username Are Above Max Value', 'Test Type': 'Negative', 'Request_Body': {'firstName': 'ZeFbtDdfueEvRsjhWRVSbkZrSkljFvqiqwXsXBRDkBgAtahBKUq', 'lastName': 'ROuwrDMQFrCZmlyIXFDmgKPSCq', 'username': 'jkYOhc2053532', 'password': 'sR3@#]'}}"}], "start": 1670168739083, "stop": 1670168739907, "uuid": "0958636d-389f-4ff2-af2e-4cd7d92eff7a", "historyId": "92fc222e2d62679912bb6f47f859f879", "testCaseId": "bd51a8de3249e024de618e4e17a0a343", "fullName": "tests.test_api.TestApi#test_register", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "DESKTOP-EGG762M"}, {"name": "thread", "value": "11972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}